### ISSUE TITLE
What is the principle of optimize()   

### ISSUE THREAD

**Issue by ohisamelie** [panosz/alpha_shapes#13]
What is the principle of shaper.optimize() ? Do you have any reference materials?

**Comment by panosz** [comment]
`optimize` tries to calculate the alpha shape with the minimum number of triangles so that no vertices of the initial triangulation are left uncovered. It then returns the alpha value and the corresponding shape.

I am sorry, I don't have any reference material. I just thought it would be fun to implement this :).

**Comment by panosz** [comment]
I guess we should add a docstring to document this method. 
Related to #6
